"""Add a reserving user ID

Revision ID: 21eeaed6d2b6
Revises: eddebe0f4fd8
Create Date: 2022-09-06 17:05:40.488218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21eeaed6d2b6'
down_revision = 'eddebe0f4fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('creating_user_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('reserving_user_id', sa.Integer(), nullable=True))
    op.drop_constraint('posts_user_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['creating_user_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'users', ['reserving_user_id'], ['id'])
    op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_user_id_fkey', 'posts', 'users', ['user_id'], ['id'])
    op.drop_column('posts', 'reserving_user_id')
    op.drop_column('posts', 'creating_user_id')
    # ### end Alembic commands ###
